sudo: false
language: node_js
node_js:
  - v10
before_script:
  - nvm use v8
  - yarn --ignore-engines
script:
  - yarn lint
  - yarn test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5156be73e058008e1ed2
    on_success: always # options: [always|never|change] default: always
    on_failure: always # options: [always|never|change] default: always
    on_start: never # options: [always|never|change] default: always
